[tox]
env_list =
    py38-dj22
    py39-dj22
    py38-dj32
    py310-dj32
    py38-dj42
    py312-dj42
    py310-dj50
    py312-dj50
    py312-dj60
    py314-dj60

[testenv]
package = wheel
wheel_build_env = .pkg
deps =
    pytest
    pytest-django
    pytest-cov
    dj22: django>=2.2,<2.3
    dj32: django>=3.2,<3.3
    dj42: django>=4.2,<4.3
    dj50: django>=5.0,<5.1
    dj60: django>=6.0,<6.1
commands =
    pytest {posargs}
